# Site settings
title: NYC Scavenger Hunt
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://nycscavengerhunt.github.io/" # the base hostname & protocol for your site
author: Scott

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
