# User config
# url: "https://nycscavengerhunt.github.io/"
author: "ScavengerHunt"
tagline: "Scavenger Hunt in NYC for Margaret's Birthday"
description: "Follow the clus and reach the prize!"
keywords: "scavenger hunt nyc birthday party"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
